services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - sns-db:/var/lib/mysql

  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  sns-db:
    name: sns-db
